
import { useState } from "react"

type EmailCardProps = {
  summary: string
  confidence?: number
  subject?: string
  sender?: string
  has_attachment?: boolean
}

export function EmailCard({ summary, confidence, subject, sender, has_attachment }: EmailCardProps) {
  
  const [expanded, setExpanded] = useState(false)

  const MAX_LENGTH = 140
  const isLong = summary.length > MAX_LENGTH

  const shortSummary = summary.slice(0, MAX_LENGTH) + "..."

  return (
    <div className="p-4 rounded-xl border border-zinc-200 dark:border-zinc-700 
                    bg-white dark:bg-zinc-900 shadow-sm transition 
                    hover:shadow-md hover:border-zinc-300 dark:hover:border-zinc-600" onMouseLeave={() => setExpanded(false)}>

      {/* SUBJECT + SENDER */}
      <div className="mb-2">
        <div className="text-sm font-semibold text-zinc-900 dark:text-zinc-100">
          {subject || "Email Summary"}
        </div>

        {sender && (
          <div className="text-xs text-pink-500 dark:text-pink-400 mt-0.5">
            {sender}
          </div>
        )}

        {has_attachment && (
          <div className="text-xs mt-1 inline-flex items-center gap-1 text-blue-600 dark:text-blue-400">
            📎 <span className="font-medium"> Has Attachment(s)</span>
          </div>
        )}
      </div>

      {/* SUMMARY */}
      {/* <p className="text-sm text-zinc-700 dark:text-zinc-300 leading-relaxed mt-1 line-clamp-4"> */}
      <p
  className={`text-sm text-zinc-700 dark:text-zinc-300 leading-relaxed mt-1 transition-all duration-300 ease-in-out overflow-hidden ${
    expanded ? "max-h-[500px]" : "max-h-[5.5rem] line-clamp-4"
  }`}
>
        {/* {summary} */}
          {expanded || !isLong ? summary : shortSummary}

        {isLong && !expanded && (
          <span
            onClick={() => setExpanded(true)}
            className="ml-2 text-blue-600 dark:text-blue-400 cursor-pointer font-medium"
          >
            Read more
          </span>
        )}    


      </p>

      {/* FOOTER */}
      <div className="mt-3 flex items-center justify-between text-xs">
        
        <span className="text-blue-600 dark:text-blue-400 font-medium">
          Generated by Nemo
        </span>

        {confidence !== undefined && (
          <span className="px-2 py-1 rounded-full bg-blue-100 dark:bg-blue-900/30 
                          text-blue-700 dark:text-blue-300 font-semibold shadow-sm">
            {Math.round(confidence * 100)}% confidence
          </span>
        )}
      </div>

    </div>
  )
}